services:
  web:
    build:
      context: .
      args:
        VITE_PRIVATE_LINK_SERVICE_HOST: ${VITE_PRIVATE_LINK_SERVICE_HOST:-http://localhost:8787}
        VITE_PRIVATE_LINK_SERVICE_PUBKEY: ${VITE_PRIVATE_LINK_SERVICE_PUBKEY:-CHANGE_THIS_BEFORE_BUILDING}
    env_file:
      - .env
    depends_on:
      - private-link-proxy
    ports:
      - "3000:80"

  private-link-proxy:
    build:
      context: .
      target: private-link-proxy
    env_file:
      - ./services/private-link-proxy/.env
    ports:
      - "${PRIVATE_LINK_PROXY_PORT:-8787}:8787"
